---
- name: Install neovim dependencies
  become: yes
  pacman:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 400
  vars:
    packages:
      - python-pip
      - python-setuptools

- name: Install neovim
  become: yes
  pacman:
    name: neovim
    state: present
    update_cache: yes
    cache_valid_time: 400
