---
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Install Python deps
  become: yes
  pip:
    name: "{{ packages }}"
    executable: "pip3"
  vars:
    packages:
      - setuptools
      - wheel
      - neovim
